package sighteaddons.ui.render

import net.minecraft.client.gui.GuiGraphicsExtractor
import net.minecraft.client.renderer.RenderPipelines
import net.minecraft.resources.Identifier

/**
 * The one texture this UI draws from, and the coordinates of every region on it.
 *
 * One sheet is not an accident of packing. Every shape drawn through here shares a single
 * `TextureSetup`, so the GUI renderer batches all of them into one GPU draw; a second texture would
 * split that batch. It is also the whole of the mod's `textures/` directory, in a mod whose README
 * makes a point of shipping none — 7 KB, generated by `tools/gen_ui_sheet.py`, which is checked in so
 * the asset has a source rather than being a binary nobody can reproduce.
 *
 * Everything on the sheet is white with a varying alpha; colour arrives as the `tint` argument, which
 * is what lets one sheet serve both themes and every state. Coordinates below mirror the generator.
 * Change one without the other and the blits are silently wrong.
 */
internal object Sheet {

    val TEXTURE: Identifier = Identifier.fromNamespaceAndPath("sighteaddons", "textures/gui/ui_sheet.png")

    const val TEX_SIZE = 256

    /** Radii with an authored corner, ascending. A requested radius snaps down to one of these. */
    val RADII = intArrayOf(4, 8, 12, 16)

    /** Quadrant order, matching the generator: top-left, top-right, bottom-left, bottom-right. */
    const val TOP_LEFT = 0
    const val TOP_RIGHT = 1
    const val BOTTOM_LEFT = 2
    const val BOTTOM_RIGHT = 3

    private const val GUTTER = 8
    private const val AUTHOR_SCALE = 2

    // Origins on the sheet, indexed the same way as RADII.
    private val CORNER_X = intArrayOf(0, 0, 0, 0)
    private val CORNER_Y = intArrayOf(0, 16, 40, 72)
    private val RING_X = intArrayOf(96, 96, 96, 96)
    private val RING_Y = intArrayOf(112, 128, 152, 184)

    private const val RAMP_X = 0
    private const val RAMP_Y = 112
    private const val RAMP_W = 64
    private const val RAMP_H = 8

    private const val SHADOW_X = 0
    private const val SHADOW_Y = 128
    private const val SHADOW_SIZE = 96

    /** The nine-slice border of the shadow region, in texture pixels. */
    const val SHADOW_INSET = 24

    /** Index into [RADII] for the largest authored radius not exceeding [radius]. */
    fun radiusIndex(radius: Int): Int {
        var index = 0
        for (i in RADII.indices) {
            if (RADII[i] <= radius) index = i
        }
        return index
    }

    /**
     * A filled quarter disc — the material of one rounded corner.
     *
     * [size] is the destination size in GUI pixels and is normally the radius itself; the source is
     * authored at twice that, so the GPU scales by two in either direction rather than by four.
     */
    fun corner(graphics: GuiGraphicsExtractor, x: Int, y: Int, radiusIndex: Int, quadrant: Int, size: Int, tint: Int) {
        val source = RADII[radiusIndex] * AUTHOR_SCALE
        blit(
            graphics,
            x, y, size, size,
            CORNER_X[radiusIndex] + quadrant * (source + GUTTER), CORNER_Y[radiusIndex],
            source, source, tint,
        )
    }

    /** The hairline arc of that same corner. */
    fun ring(graphics: GuiGraphicsExtractor, x: Int, y: Int, radiusIndex: Int, quadrant: Int, size: Int, tint: Int) {
        val source = RADII[radiusIndex] * AUTHOR_SCALE
        blit(
            graphics,
            x, y, size, size,
            RING_X[radiusIndex] + quadrant * (source + GUTTER), RING_Y[radiusIndex],
            source, source, tint,
        )
    }

    /**
     * A soft `0 -> 1 -> 0` sweep stretched across [width].
     *
     * One draw at any width, because the sheet is loaded with `blur: true` and the GPU filters
     * linearly. The obvious alternative — stacking N one-pixel columns of a vertical `fillGradient` —
     * costs two allocations per column and would be 320 objects per frame for a 160px shimmer.
     */
    fun rampH(graphics: GuiGraphicsExtractor, x: Int, y: Int, width: Int, height: Int, tint: Int) {
        blit(graphics, x, y, width, height, RAMP_X, RAMP_Y, RAMP_W, RAMP_H, tint)
    }

    /**
     * A pre-blurred drop shadow, nine-sliced so one sprite serves every card size.
     *
     * One shadow sprite also serves every *radius*: a blur wide enough to read as a shadow washes out
     * the difference between a radius-4 and a radius-16 silhouette entirely.
     *
     * [spread] is how far the shadow extends beyond the rectangle on each side, and [offset] pushes
     * it down — a light source above, the only lighting convention this UI has.
     */
    fun shadow(
        graphics: GuiGraphicsExtractor,
        x: Int, y: Int, width: Int, height: Int,
        spread: Int, offset: Int, tint: Int,
    ) {
        val left = x - spread
        val top = y - spread + offset
        val right = x + width + spread
        val bottom = y + height + spread + offset

        // Corner pieces keep their authored size; the edges and the middle stretch. Written by hand
        // rather than through blitSprite, whose default nine-slice tiles the edges and would repeat a
        // visible gradient rather than stretch it.
        val inset = SHADOW_INSET
        val far = SHADOW_SIZE - inset
        val midW = (right - left) - inset * 2
        val midH = (bottom - top) - inset * 2
        if (midW <= 0 || midH <= 0) return

        blit(graphics, left, top, inset, inset, SHADOW_X, SHADOW_Y, inset, inset, tint)
        blit(graphics, right - inset, top, inset, inset, SHADOW_X + far, SHADOW_Y, inset, inset, tint)
        blit(graphics, left, bottom - inset, inset, inset, SHADOW_X, SHADOW_Y + far, inset, inset, tint)
        blit(graphics, right - inset, bottom - inset, inset, inset, SHADOW_X + far, SHADOW_Y + far, inset, inset, tint)

        blit(graphics, left + inset, top, midW, inset, SHADOW_X + inset, SHADOW_Y, far - inset, inset, tint)
        blit(graphics, left + inset, bottom - inset, midW, inset, SHADOW_X + inset, SHADOW_Y + far, far - inset, inset, tint)
        blit(graphics, left, top + inset, inset, midH, SHADOW_X, SHADOW_Y + inset, inset, far - inset, tint)
        blit(graphics, right - inset, top + inset, inset, midH, SHADOW_X + far, SHADOW_Y + inset, inset, far - inset, tint)

        blit(graphics, left + inset, top + inset, midW, midH, SHADOW_X + inset, SHADOW_Y + inset, far - inset, far - inset, tint)
    }

    /**
     * The eleven-argument blit: an arbitrary source rect to an arbitrary destination rect, tinted.
     *
     * Kept private and wrapped so the argument order — which is destination size *before* source
     * size, and easy to transpose — is written once.
     */
    private fun blit(
        graphics: GuiGraphicsExtractor,
        x: Int, y: Int, drawWidth: Int, drawHeight: Int,
        u: Int, v: Int, sourceWidth: Int, sourceHeight: Int,
        tint: Int,
    ) {
        graphics.blit(
            RenderPipelines.GUI_TEXTURED,
            TEXTURE,
            x, y,
            u.toFloat(), v.toFloat(),
            drawWidth, drawHeight,
            sourceWidth, sourceHeight,
            TEX_SIZE, TEX_SIZE,
            tint,
        )
    }
}
